version: 0.1.{build}
configuration:
- UnitTests
platform: x86
build:
  project: FileIO.sln
test_script:
-  cmd: vstest.console /logger:Appveyor /inIsolation /platform:%Platform% bin\%Configuration%\%Platform2%\FileIOTests.dll
